engineStrict: true
pmOnFail: error

allowBuilds:
  cwebp-bin: true
  esbuild: true
  gifsicle: true
  jpegtran-bin: true
  mozjpeg: true
  optipng-bin: true
  pngquant-bin: true
  vite-plugin-vue-tailwind-auto-reference: true

publicHoistPattern:
  - eslint-plugin-perfectionist
  - eslint-flat-config-utils
  - lightningcss # @tailwindcss/vite
  - lodash-es # tdesign-vue-next 依赖 lodash-es
  - '@types/lodash-es'
  - dayjs # tdesign-vue-next 依赖 dayjs
shellEmulator: true
trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 10080 # 忽略超过 7 天（10080 分钟）的版本检测
