/**
 * 该文件为脚本自动生成文件，请勿随意修改。如需修改请联系 PMC
 * https://github.com/TDesignOteam/tdesign-api
 * eslint-disable
 */
declare module 'vue' {
  export interface GlobalComponents {
    // Icon: (typeof import('tdesign-icons-vue-next'))['Icon']
    // IconFont: (typeof import('tdesign-icons-vue-next'))['IconFont']
    TAffix: (typeof import('tdesign-vue-next'))['Affix']
    TAlert: (typeof import('tdesign-vue-next'))['Alert']
    TAnchor: (typeof import('tdesign-vue-next'))['Anchor']
    TAnchorItem: (typeof import('tdesign-vue-next'))['AnchorItem']
    TAnchorTarget: (typeof import('tdesign-vue-next'))['AnchorTarget']
    TAside: (typeof import('tdesign-vue-next'))['Aside']
    TAutoComplete: (typeof import('tdesign-vue-next'))['AutoComplete']
    TAvatar: (typeof import('tdesign-vue-next'))['Avatar']
    TAvatarGroup: (typeof import('tdesign-vue-next'))['AvatarGroup']
    TBackTop: (typeof import('tdesign-vue-next'))['BackTop']
    TBadge: (typeof import('tdesign-vue-next'))['Badge']
    TBaseTable: (typeof import('tdesign-vue-next'))['BaseTable']
    TBreadcrumb: (typeof import('tdesign-vue-next'))['Breadcrumb']
    TBreadcrumbItem: (typeof import('tdesign-vue-next'))['BreadcrumbItem']
    TButton: (typeof import('tdesign-vue-next'))['Button']
    TCalendar: (typeof import('tdesign-vue-next'))['Calendar']
    // TCard: (typeof import('tdesign-vue-next'))['Card']
    TCard: (typeof import('@/components/tDesignReset/TCard.vue'))['default']
    TCascader: (typeof import('tdesign-vue-next'))['Cascader']
    TCheckbox: (typeof import('tdesign-vue-next'))['Checkbox']
    // TCheckboxGroup: (typeof import('tdesign-vue-next'))['CheckboxGroup']
    TCheckboxGroup: (typeof import('@/components/tDesignReset/TCheckboxGroup.vue'))['default']
    TCheckTag: (typeof import('tdesign-vue-next'))['CheckTag']
    TCheckTagGroup: (typeof import('tdesign-vue-next'))['CheckTagGroup']
    TCol: (typeof import('tdesign-vue-next'))['Col']
    TCollapse: (typeof import('tdesign-vue-next'))['Collapse']
    TCollapsePanel: (typeof import('tdesign-vue-next'))['CollapsePanel']
    TColorPicker: (typeof import('tdesign-vue-next'))['ColorPicker']
    TColorPickerPanel: (typeof import('tdesign-vue-next'))['ColorPickerPanel']
    TComment: (typeof import('tdesign-vue-next'))['Comment']
    TConfigProvider: (typeof import('tdesign-vue-next'))['ConfigProvider']
    TContent: (typeof import('tdesign-vue-next'))['Content']
    TDatePicker: (typeof import('tdesign-vue-next'))['DatePicker']
    TDatePickerPanel: (typeof import('tdesign-vue-next'))['DatePickerPanel']
    TDateRangePicker: (typeof import('tdesign-vue-next'))['DateRangePicker']
    TDateRangePickerPanel: (typeof import('tdesign-vue-next'))['DateRangePickerPanel']
    TDescriptions: (typeof import('tdesign-vue-next'))['Descriptions']
    TDescriptionsItem: (typeof import('tdesign-vue-next'))['DescriptionsItem']
    TDialog: (typeof import('tdesign-vue-next'))['Dialog']
    TDialogCard: (typeof import('tdesign-vue-next'))['DialogCard']
    TDivider: (typeof import('tdesign-vue-next'))['Divider']
    TDrawer: (typeof import('tdesign-vue-next'))['Drawer']
    TDropdown: (typeof import('tdesign-vue-next'))['Dropdown']
    TDropdownItem: (typeof import('tdesign-vue-next'))['DropdownItem']
    TEmpty: (typeof import('tdesign-vue-next'))['Empty']
    TEnhancedTable: (typeof import('tdesign-vue-next'))['EnhancedTable']
    TFooter: (typeof import('tdesign-vue-next'))['Footer']
    // TForm: (typeof import('tdesign-vue-next'))['Form']
    TForm: (typeof import('@/components/tDesignReset/TForm.vue'))['default']
    TFormItem: (typeof import('tdesign-vue-next'))['FormItem']
    TGuide: (typeof import('tdesign-vue-next'))['Guide']
    THeader: (typeof import('tdesign-vue-next'))['Header']
    THeadMenu: (typeof import('tdesign-vue-next'))['HeadMenu']
    // TIcon: (typeof import('tdesign-vue-next'))['Icon']
    // TImage: (typeof import('tdesign-vue-next'))['Image']
    TImage: (typeof import('@/components/tDesignReset/TImage.vue'))['default']
    TImageViewer: (typeof import('tdesign-vue-next'))['ImageViewer']
    // TInput: (typeof import('tdesign-vue-next'))['Input']
    TInput: (typeof import('@/components/tDesignReset/TInput.vue'))['default']
    TInputAdornment: (typeof import('tdesign-vue-next'))['InputAdornment']
    TInputGroup: (typeof import('tdesign-vue-next'))['InputGroup']
    TInputNumber: (typeof import('tdesign-vue-next'))['InputNumber']
    TLayout: (typeof import('tdesign-vue-next'))['Layout']
    TLink: (typeof import('tdesign-vue-next'))['Link']
    TList: (typeof import('tdesign-vue-next'))['List']
    TListItem: (typeof import('tdesign-vue-next'))['ListItem']
    TListItemMeta: (typeof import('tdesign-vue-next'))['ListItemMeta']
    TLoading: (typeof import('tdesign-vue-next'))['Loading']
    TMenu: (typeof import('tdesign-vue-next'))['Menu']
    TMenuGroup: (typeof import('tdesign-vue-next'))['MenuGroup']
    TMenuItem: (typeof import('tdesign-vue-next'))['MenuItem']
    TMessage: (typeof import('tdesign-vue-next'))['Message']
    TNotification: (typeof import('tdesign-vue-next'))['Notification']
    TOption: (typeof import('tdesign-vue-next'))['Option']
    TOptionGroup: (typeof import('tdesign-vue-next'))['OptionGroup']
    TPagination: (typeof import('tdesign-vue-next'))['Pagination']
    TPaginationMini: (typeof import('tdesign-vue-next'))['PaginationMini']
    TPopconfirm: (typeof import('tdesign-vue-next'))['Popconfirm']
    TPopup: (typeof import('tdesign-vue-next'))['Popup']
    TPrimaryTable: (typeof import('tdesign-vue-next'))['PrimaryTable']
    TProgress: (typeof import('tdesign-vue-next'))['Progress']
    TQrcode: (typeof import('tdesign-vue-next'))['QRCode']
    TRadio: (typeof import('tdesign-vue-next'))['Radio']
    TRadioButton: (typeof import('tdesign-vue-next'))['RadioButton']
    // TRadioGroup: (typeof import('tdesign-vue-next'))['RadioGroup']
    TRadioGroup: (typeof import('@/components/tDesignReset/TRadioGroup.vue'))['default']
    TRangeInput: (typeof import('tdesign-vue-next'))['RangeInput']
    TRangeInputPopup: (typeof import('tdesign-vue-next'))['RangeInputPopup']
    TRate: (typeof import('tdesign-vue-next'))['Rate']
    TRow: (typeof import('tdesign-vue-next'))['Row']
    TSearch: (typeof import('tdesign-vue-next'))['Search']
    TSelect: (typeof import('tdesign-vue-next'))['Select']
    TSelectInput: (typeof import('tdesign-vue-next'))['SelectInput']
    TSkeleton: (typeof import('tdesign-vue-next'))['Skeleton']
    TSlider: (typeof import('tdesign-vue-next'))['Slider']
    TSpace: (typeof import('tdesign-vue-next'))['Space']
    TStatistic: (typeof import('tdesign-vue-next'))['Statistic']
    TStepItem: (typeof import('tdesign-vue-next'))['StepItem']
    TSteps: (typeof import('tdesign-vue-next'))['Steps']
    TStickyItem: (typeof import('tdesign-vue-next'))['StickyItem']
    TStickyTool: (typeof import('tdesign-vue-next'))['StickyTool']
    TSubmenu: (typeof import('tdesign-vue-next'))['Submenu']
    TSwiper: (typeof import('tdesign-vue-next'))['Swiper']
    TSwiperItem: (typeof import('tdesign-vue-next'))['SwiperItem']
    TSwitch: (typeof import('tdesign-vue-next'))['Switch']
    TTable: (typeof import('tdesign-vue-next'))['Table']
    TTabPanel: (typeof import('tdesign-vue-next'))['TabPanel']
    TTabs: (typeof import('tdesign-vue-next'))['Tabs']
    TTag: (typeof import('tdesign-vue-next'))['Tag']
    TTagInput: (typeof import('tdesign-vue-next'))['TagInput']
    TTextarea: (typeof import('tdesign-vue-next'))['Textarea']
    TTimeline: (typeof import('tdesign-vue-next'))['Timeline']
    TTimelineItem: (typeof import('tdesign-vue-next'))['TimelineItem']
    TTimePicker: (typeof import('tdesign-vue-next'))['TimePicker']
    TTimeRangePicker: (typeof import('tdesign-vue-next'))['TimeRangePicker']
    TTooltip: (typeof import('tdesign-vue-next'))['Tooltip']
    TTooltipLite: (typeof import('tdesign-vue-next'))['TooltipLite']
    TTransfer: (typeof import('tdesign-vue-next'))['Transfer']
    TTree: (typeof import('tdesign-vue-next'))['Tree']
    TTreeSelect: (typeof import('tdesign-vue-next'))['TreeSelect']
    TTypography: (typeof import('tdesign-vue-next'))['Typography']
    TTypographyParagraph: (typeof import('tdesign-vue-next'))['Paragraph']
    TTypographyText: (typeof import('tdesign-vue-next'))['Text']
    TTypographyTitle: (typeof import('tdesign-vue-next'))['Title']
    TUpload: (typeof import('tdesign-vue-next'))['Upload']
    TWatermark: (typeof import('tdesign-vue-next'))['Watermark']
  }
}

export {}
